export const projectsData = {
    BG: [
        {
            id: 1,
            title: "Ремонт на баня",
            date: "2023-05-10",
            description:
                "Пълно обновяване на баня с нови плочки, санитария и осветление. Пълно обновяване на баня с нови плочки, санитария и осветление. Пълно обновяване на баня с нови плочки, санитария и осветление. Пълно обновяване на баня с нови плочки, санитария и осветление. Пълно обновяване на баня с нови плочки, санитария и осветление. Пълно обновяване на баня с нови плочки, санитария и осветление. Пълно обновяване на баня с нови плочки, санитария и осветление. Пълно обновяване на баня с нови плочки, санитария и осветление. Пълно обновяване на баня с нови плочки, санитария и осветление. Пълно обновяване на баня с нови плочки, санитария и осветление. Пълно обновяване на баня с нови плочки, санитария и осветление. Пълно обновяване на баня с нови плочки, санитария и осветление.",
            imageSrc: "/images/services/tiles.jpg",
            price: "8000",
        },
        {
            id: 2,
            title: "Монтаж на гипсокартон",
            date: "2023-06-15",
            description: "Инсталиране на гипсокартонени стени и тавани в нова сграда.",
            imageSrc: "/images/services/drywall.jpg",
            price: "50000",
        },
        {
            id: 3,
            title: "Боядисване на апартамент",
            date: "2023-07-20",
            description: "Професионално боядисване на цял апартамент с висококачествени бои.",
            imageSrc: "/images/services/paint.jpg",
            price: "3000",
        },
        {
            id: 4,
            title: "ВиК услуги",
            date: "2023-08-05",
            description: "Ремонт и подмяна на водопроводни и канализационни системи.",
            imageSrc: "/images/services/plumbing.jpg",
            price: "4000",
        },
        {
            id: 5,
            title: "Електро услуги",
            date: "2023-09-12",
            description: "Инсталация и ремонт на електрически системи в жилищни и търговски сгради.",
            imageSrc: "/images/services/electrical.jpg",
            price: "6000",
        },
    ],
    EN: [
        {
            id: 1,
            title: "Bathroom Renovation",
            date: "2023-05-10",
            description:
                "Complete bathroom makeover with new tiles, sanitary ware, and lighting. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iusto labore ipsum harum dolorum fuga repellat magni doloremque reiciendis enim est, possimus at! Sed enim magni explicabo corrupti nam culpa facere. Nulla eveniet ipsa ut explicabo sunt voluptatum quibusdam maxime incidunt voluptas pariatur voluptatibus laborum, dignissimos inventore ea optio nostrum cumque debitis cupiditate quaerat soluta? Ea, labore error? Inventore consequatur perferendis reprehenderit aperiam numquam praesentium sed rem doloremque dolorum provident cupiditate dolorem ut ratione eveniet quod soluta tempore, hic dicta delectus placeat. Molestias error tenetur quod voluptatum ex quae dignissimos ut provident quia reiciendis repudiandae fuga, autem necessitatibus, nisi dolorum voluptatibus!",
            imageSrc: "/images/services/tiles.jpg",
            price: "8000",
        },
        {
            id: 2,
            title: "Drywall Installation",
            date: "2023-06-15",
            description: "Installation of drywall walls and ceilings in a new building.",
            imageSrc: "/images/services/drywall.jpg",
            price: "50,000",
        },
        {
            id: 3,
            title: "Apartment Painting",
            date: "2023-07-20",
            description: "Professional painting of an entire apartment with high-quality paints.",
            imageSrc: "/images/services/paint.jpg",
            price: "3000",
        },
        {
            id: 4,
            title: "Plumbing Services",
            date: "2023-08-05",
            description: "Repair and replacement of plumbing and sewage systems.",
            imageSrc: "/images/services/plumbing.jpg",
            price: "4000",
        },
        {
            id: 5,
            title: "Electrical Services",
            date: "2023-09-12",
            description: "Installation and repair of electrical systems in residential and commercial buildings.",
            imageSrc: "/images/services/electrical.jpg",
            price: "6000",
        },
    ],
};
