export const electrical = {
    bg: [
        {
            id: "1",
            category_slug: "electrical",
            title: "Изработване на електро-проект на жилищни или офис сгради.",
            unit: "брой",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "2",
            category_slug: "electrical",
            title: "Монтаж, Демонтаж на слаботокова електроинсталация.",
            unit: "линеен метър",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "3",
            category_slug: "electrical",
            title: "Монтаж, Демонтаж на силнотокова електроинсталация.",
            unit: "линеен метър",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "4",
            category_slug: "electrical",
            title: "Монтаж, Демонтаж на електроразпределителни табла.",
            unit: "брой",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "5",
            category_slug: "electrical",
            title: "Изкопаване на канали и отвори в тухла или бетон.",
            unit: "линеен метър",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "6",
            category_slug: "electrical",
            title: "Полагане на електроинсталационни тръби.",
            unit: "линеен метър",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "7",
            category_slug: "electrical",
            title: "Полагане на кабели с различни вид и сечение.",
            unit: "линеен метър",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "8",
            category_slug: "electrical",
            title: "Монтаж, Демонтаж на Разклонителни кутии, Конзоли",
            unit: "брой",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "9",
            category_slug: "electrical",
            title: "Монтаж, Демонтаж на ключове или контакти.",
            unit: "брой",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "10",
            category_slug: "electrical",
            title: "Монтаж, Демонтаж на осветителни тела.",
            unit: "брой",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "11",
            category_slug: "electrical",
            title: "Монтаж и Демонтаж на Заземителна или Мълниезащитна инсталация.",
            unit: "брой",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "12",
            category_slug: "electrical",
            title: "Прозвъняване и Тест на Електроинсталация.",
            unit: "брой",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "13",
            category_slug: "electrical",
            title: "Измерване и Тест на нова или стара електроинсталация.",
            unit: "брой",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "14",
            category_slug: "electrical",
            title: "Отстраняване на повреди на слаботокова електроинсталация.",
            unit: "брой",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "15",
            category_slug: "electrical",
            title: "Отстраняване на повреди на силнотокова електроинсталация.",
            unit: "брой",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
    ],
    en: [
        {
            id: "1",
            category_slug: "electrical",
            title: "Creating electrical project for residential or office buildings.",
            unit: "piece",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "2",
            category_slug: "electrical",
            title: "Installation, Dismantling of low-voltage electrical installation.",
            unit: "linear meter",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "3",
            category_slug: "electrical",
            title: "Installation, Dismantling of high-voltage electrical installation.",
            unit: "linear meter",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "4",
            category_slug: "electrical",
            title: "Installation, Dismantling of electrical distribution boards.",
            unit: "piece",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "5",
            category_slug: "electrical",
            title: "Excavation of channels and openings in brick or concrete.",
            unit: "linear meter",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "6",
            category_slug: "electrical",
            title: "Laying of electrical installation pipes.",
            unit: "linear meter",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "7",
            category_slug: "electrical",
            title: "Laying cables of different types and sections.",
            unit: "linear meter",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "8",
            category_slug: "electrical",
            title: "Installation, Dismantling of Junction boxes, Consoles",
            unit: "piece",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "9",
            category_slug: "electrical",
            title: "Installation, Dismantling of switches or sockets.",
            unit: "piece",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "10",
            category_slug: "electrical",
            title: "Installation, Dismantling of lighting fixtures.",
            unit: "piece",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "11",
            category_slug: "electrical",
            title: "Installation and Dismantling of Grounding or Lightning Protection installation.",
            unit: "piece",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "12",
            category_slug: "electrical",
            title: "Tracing and Testing of Electrical Installation.",
            unit: "piece",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "13",
            category_slug: "electrical",
            title: "Measurement and Testing of new or old electrical installation.",
            unit: "piece",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "14",
            category_slug: "electrical",
            title: "Troubleshooting of low-voltage electrical installation.",
            unit: "piece",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "15",
            category_slug: "electrical",
            title: "Troubleshooting of high-voltage electrical installation.",
            unit: "piece",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
    ],
};

export const painting = {
    bg: [
        {
            id: "1",
            category_slug: "painting",
            title: "Боядисване на стени - вътрешно",
            unit: "кв.м",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "2",
            category_slug: "painting",
            title: "Боядисване на стени - външно",
            unit: "кв.м",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "3",
            category_slug: "painting",
            title: "Боядисване на тавани",
            unit: "кв.м",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "4",
            category_slug: "painting",
            title: "Боядисване на дървени повърхности",
            unit: "кв.м",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "5",
            category_slug: "painting",
            title: "Боядисване на метални повърхности",
            unit: "кв.м",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
    ],
    en: [
        {
            id: "1",
            category_slug: "painting",
            title: "Interior Wall Painting",
            unit: "sq.m",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "2",
            category_slug: "painting",
            title: "Exterior Wall Painting",
            unit: "sq.m",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "3",
            category_slug: "painting",
            title: "Ceiling Painting",
            unit: "sq.m",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "4",
            category_slug: "painting",
            title: "Wood Surface Painting",
            unit: "sq.m",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "5",
            category_slug: "painting",
            title: "Metal Surface Painting",
            unit: "sq.m",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
    ],
};

export const plumbing = {
    bg: [
        {
            id: "1",
            category_slug: "plumbing",
            title: "Ремонт на течове",
            unit: "брой",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "2",
            category_slug: "plumbing",
            title: "Монтаж на тръби",
            unit: "метър",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "3",
            category_slug: "plumbing",
            title: "Монтаж на кранове",
            unit: "брой",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "4",
            category_slug: "plumbing",
            title: "Монтаж на тоалетни",
            unit: "брой",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
    ],
    en: [
        {
            id: "1",
            category_slug: "plumbing",
            title: "Leak Repair",
            unit: "piece",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "2",
            category_slug: "plumbing",
            title: "Pipe Installation",
            unit: "meter",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "3",
            category_slug: "plumbing",
            title: "Faucet Installation",
            unit: "piece",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "4",
            category_slug: "plumbing",
            title: "Toilet Installation",
            unit: "piece",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
    ],
};

export const drywall = {
    bg: [
        {
            id: "1",
            category_slug: "drywall",
            title: "Монтаж на гипсокартон",
            unit: "кв.м",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "2",
            category_slug: "drywall",
            title: "Ремонт на гипсокартон",
            unit: "кв.м",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "3",
            category_slug: "drywall",
            title: "Шпакловане и    боядисване на гипсокартон",
            unit: "кв.м",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
    ],
    en: [
        {
            id: "1",
            category_slug: "drywall",
            title: "Drywall Installation",
            unit: "sq.m",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "2",
            category_slug: "drywall",
            title: "Drywall Repair",
            unit: "sq.m",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
        {
            id: "3",
            category_slug: "drywall",
            title: "Drywall Finishing and Painting",
            unit: "sq.m",
            image_src: "/images/service_details_cards/electro/Electrical-Services.jpg",
            price_from: 100,
            price_to: 500,
        },
    ],
};

export const services = [
    {
        id: 1,
        category_slug: "painting",
        bg: painting.bg,
        en: painting.en,
    },
    {
        id: 2,
        category_slug: "plumbing",
        bg: plumbing.bg,
        en: plumbing.en,
    },
    {
        id: 3,
        category_slug: "drywall",
        bg: drywall.bg,
        en: drywall.en,
    },
    {
        id: 4,
        category_slug: "electrical",
        bg: electrical.bg,
        en: electrical.en,
    },
];
