export const electrical = {
    BG: [{
        id: '1',
        key: '',
        category: 'electrical',
        pathname: 'електро услуги',
        title: "Изработване на електро-проект на жилищни или офис сгради.",
        unit: "брой",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "500 - 800",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'електро услуги',
        title: "Монтаж, Демонтаж на слаботокова електроинсталация.",
        unit: "линеен метър",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'електро услуги',
        title: "Монтаж, Демонтаж на силнотокова електроинсталация.",
        unit: "линеен метър",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'електро услуги',
        title: "Монтаж, Демонтаж на електроразпределителни табла.",
        unit: "брой",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'електро услуги',
        title: "Изкопаване на канали и отвори в тухла или бетон.",
        unit: "линеен метър",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'електро услуги',
        title: "Полагане на електроинсталационни тръби.",
        unit: "линеен метър",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'електро услуги',
        title: "Полагане на кабели с различни вид и сечение.",
        unit: "линеен метър",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'електро услуги',
        title: "Монтаж, Демонтаж на Разклонителни кутии, Конзоли",
        unit: "брой",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'електро услуги',
        title: "Монтаж, Демонтаж на ключове или контакти.",
        unit: "брой",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'електро услуги',
        title: "Монтаж, Демонтаж на осветителни тела.",
        unit: "брой",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'електро услуги',
        title: "Монтаж и Демонтаж на Заземителна или Мълниезащитна инсталация.",
        unit: "брой",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'електро услуги',
        title: "Прозвъняване и Тест на Електроинсталация.",
        unit: "брой",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'електро услуги',
        title: "Измерване и Тест на нова или стара електроинсталация.",
        unit: "брой",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'електро услуги',
        title: "Отстраняване на повреди на слаботокова електроинсталация.",
        unit: "брой",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'електро услуги',
        title: "Отстраняване на повреди на силнотокова електроинсталация.",
        unit: "брой",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    ],
    EN: [{
        id: '1',
        key: '',
        category: 'electrical',
        pathname: 'electrical services',
        title: "Creating electrical project for residential or office buildings.",
        unit: "piece",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "500",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'electrical services',
        title: "Installation, Dismantling of low-voltage electrical installation.",
        unit: "linear meter",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'electrical services',
        title: "Installation, Dismantling of high-voltage electrical installation.",
        unit: "linear meter",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'electrical services',
        title: "Installation, Dismantling of electrical distribution boards.",
        unit: "piece",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'electrical services',
        title: "Excavation of channels and openings in brick or concrete.",
        unit: "linear meter",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'electrical services',
        title: "Laying of electrical installation pipes.",
        unit: "linear meter",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'electrical services',
        title: "Laying cables of different types and sections.",
        unit: "linear meter",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'electrical services',
        title: "Installation, Dismantling of Junction boxes, Consoles",
        unit: "piece",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'electrical services',
        title: "Installation, Dismantling of switches or sockets.",
        unit: "piece",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'electrical services',
        title: "Installation, Dismantling of lighting fixtures.",
        unit: "piece",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'electrical services',
        title: "Installation and Dismantling of Grounding or Lightning Protection installation.",
        unit: "piece",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'electrical services',
        title: "Tracing and Testing of Electrical Installation.",
        unit: "piece",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'electrical services',
        title: "Measurement and Testing of new or old electrical installation.",
        unit: "piece",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'electrical services',
        title: "Troubleshooting of low-voltage electrical installation.",
        unit: "piece",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    {
        id: '1',
        key: 'el_outlet',
        category: 'electrical',
        pathname: 'electrical services',
        title: "Troubleshooting of high-voltage electrical installation.",
        unit: "piece",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "10",
    },
    ],
}

export const painting = {
    BG: [{
        id: '1',
        key: 'interior_wall_painting',
        category: 'painting',
        pathname: 'бояджийски услуги',
        title: "Боядисване на стени - вътрешно",
        unit: "кв.м",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "1",
    },
    {
        id: '2',
        key: 'exterior_wall_painting',
        category: 'painting',
        pathname: 'бояджийски услуги',
        title: "Боядисване на стени - външно",
        unit: "кв.м",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "1",
    },
    {
        id: '3',
        key: 'ceiling_painting',
        category: 'painting',
        pathname: 'бояджийски услуги',
        title: "Боядисване на тавани",
        unit: "кв.м",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "1",
    },
    {
        id: '4',
        key: 'wood_surface_painting',
        category: 'painting',
        pathname: 'бояджийски услуги',
        title: "Боядисване на дървени повърхности",
        unit: "кв.м",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "1",
    },
    {
        id: '5',
        key: 'metal_surface_painting',
        category: 'painting',
        pathname: 'бояджийски услуги',
        title: "Боядисване на метални повърхности",
        unit: "кв.м",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "1",
    },
    ],
    EN: [{
        id: '1',
        key: 'interior_wall_painting',
        category: 'painting',
        pathname: 'painting services',
        title: "Interior Wall Painting",
        unit: "sq.m",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "1",
    },
    {
        id: '2',
        key: 'exterior_wall_painting',
        category: 'painting',
        pathname: 'painting services',
        title: "Exterior Wall Painting",
        unit: "sq.m",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "1",
    },
    {
        id: '3',
        key: 'ceiling_painting',
        category: 'painting',
        pathname: 'painting services',
        title: "Ceiling Painting",
        unit: "sq.m",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "1",
    },
    {
        id: '4',
        key: 'wood_surface_painting',
        category: 'painting',
        pathname: 'painting services',
        title: "Wood Surface Painting",
        unit: "sq.m",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "1",
    },
    {
        id: '5',
        key: 'metal_surface_painting',
        category: 'painting',
        pathname: 'painting services',
        title: "Metal Surface Painting",
        unit: "sq.m",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "1",
    },
    ],
}

export const plumbing = {
    BG: [{
        id: '1',
        key: 'leak_repair',
        category: 'plumbing',
        pathname: 'electrical services',
        title: "Ремонт на течове",
        unit: "брой",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "100 - 300",
    },
    {
        id: '2',
        key: 'pipe_installation',
        category: 'plumbing',
        pathname: 'electrical services',
        title: "Монтаж на тръби",
        unit: "метър",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "1",
    },
    {
        id: '3',
        key: 'faucet_installation',
        category: 'plumbing',
        pathname: 'electrical services',
        title: "Монтаж на кранове",
        unit: "брой",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "1",
    },
    {
        id: '4',
        key: 'toilet_installation',
        category: 'plumbing',
        pathname: 'electrical services',
        title: "Монтаж на тоалетни",
        unit: "брой",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "1",
    },
    ],
    EN: [
        {
            id: '1',
            key: 'leak_repair',
            category: 'plumbing',
            pathname: 'electrical services',
            title: "Leak Repair",
            unit: "piece",
            imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
            price: "1",
        },
        {
            id: '2',
            key: 'pipe_installation',
            category: 'plumbing',
            pathname: 'electrical services',
            title: "Pipe Installation",
            unit: "meter",
            imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
            price: "1",
        },
        {
            id: '3',
            key: 'faucet_installation',
            category: 'plumbing',
            pathname: 'electrical services',
            title: "Faucet Installation",
            unit: "piece",
            imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
            price: "1",
        },
        {
            id: '4',
            key: 'toilet_installation',
            category: 'plumbing',
            pathname: 'electrical services',
            title: "Toilet Installation",
            unit: "piece",
            imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
            price: "1",
        },
    ]
}

export const drywall = {
    BG: [{
        id: '1',
        key: 'drywall_installation',
        category: 'drywall',
        pathname: 'electrical services',
        title: "Монтаж на гипсокартон",
        unit: "кв.м",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "1",
    },
    {
        id: '2',
        key: 'drywall_repair',
        category: 'drywall',
        pathname: 'electrical services',
        title: "Ремонт на гипсокартон",
        unit: "кв.м",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "1",
    },
    {
        id: '3',
        key: 'drywall_finishing',
        category: 'drywall',
        pathname: 'electrical services',
        title: "Шпакловане и    боядисване на гипсокартон",
        unit: "кв.м",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "1",
    },
    ],
    EN: [{
        id: '1',
        key: 'drywall_installation',
        category: 'drywall',
        pathname: 'electrical services',
        title: "Drywall Installation",
        unit: "sq.m",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "1",
    },
    {
        id: '2',
        key: 'drywall_repair',
        category: 'drywall',
        pathname: 'electrical services',
        title: "Drywall Repair",
        unit: "sq.m",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "1",
    },
    {
        id: '3',
        key: 'drywall_finishing',
        category: 'drywall',
        pathname: 'electrical services',
        title: "Drywall Finishing and Painting",
        unit: "sq.m",
        imageSrc: '/images/service_details_cards/electro/Electrical-Services.jpg',
        price: "1",
    },
    ]
}

export const services = [
    {
        id: 1,
        category: "painting",
        pathname: 'electrical services',
        BG: painting.BG,
        EN: painting.EN,
    },
    {
        id: 2,
        category: "plumbing",
        pathname: 'electrical services',
        BG: plumbing.BG,
        EN: plumbing.EN,
    },
    {
        id: 3,
        category: "drywall",
        pathname: 'electrical services',
        BG: drywall.BG,
        EN: drywall.EN,
    },
    {
        id: 4,
        category: "electrical",
        pathname: 'electrical services',
        BG: electrical.BG,
        EN: electrical.EN,
    },
]
